services:

  mysql:
    image: mysql:8.4
    container_name: banking-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - banking_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  banking-app:
    image: banking-application:latest
    container_name: banking-api
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: jdbc:mysql://mysql:3306/banking_db
      DB_USERNAME: banking_user
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 3600000
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "false"
      JPA_FORMAT_SQL: "false"

    ports:
      - "8080:8080"


volumes:
  banking_mysql_data: